angular.module("wechat.routers",[])
.config(function ($stateProvider,$urlRouterProvider) {
    $stateProvider
        .state("tab",{
            url:"/tab",
            abstract:true,
            templateUrl:"tabs.html"
        })
        .state("tab.message",{
            url:"/message",
            views:{
                "tab-message":{
                    templateUrl:"tab-message.html",
                    controller:"messageCtrl"
                }
            }
        })
        .state("tab.contacts",{
            url:"/contacts",
            views:{
                "tab-contacts":{
                    templateUrl:"tab-contacts",
                    controller:"contactsCtrl"
                }
            }
        })
        .state("tab.discover",{
            url:"/discover",
            views:{
                "tab-discover":{
                    templateUrl:"tab-discover",
                    controller:"discoverCtrl"
                }
            }
        })
        .state("tab.setting",{
            url:"/setting",
            views:{
                "tab-setting":{
                    templateUrl:"tab-setting",
                    controller:"settingCtrl"
                }
            }
        })
        .state("msgDetail",{
            url:"/msgDetail/:msgId",
            templateUrl:'msg-detail',
            controller:'msgDetailCtrl'
        })
    $urlRouterProvider.otherwise("/tab/message");
})